// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using React_Rentify.Server.Data;

#nullable disable

namespace React_Rentify.Server.Migrations.GpsDb
{
    [DbContext(typeof(GpsDbContext))]
    partial class GpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("React_Rentify.Server.Models.GPS.Gps_Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeactivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstallCarPlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InstalledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Gps_Devices");
                });

            modelBuilder.Entity("React_Rentify.Server.Models.GPS.Records.Location_Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Gps_DeviceId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IgnitionOn")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("SpeedKmh")
                        .HasColumnType("double precision");

                    b.Property<string>("StatusFlags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Gps_DeviceId");

                    b.ToTable("Location_Records");
                });

            modelBuilder.Entity("React_Rentify.Server.Models.GPS.Records.Location_Record", b =>
                {
                    b.HasOne("React_Rentify.Server.Models.GPS.Gps_Device", "Gps_Device")
                        .WithMany("Location_Records")
                        .HasForeignKey("Gps_DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gps_Device");
                });

            modelBuilder.Entity("React_Rentify.Server.Models.GPS.Gps_Device", b =>
                {
                    b.Navigation("Location_Records");
                });
#pragma warning restore 612, 618
        }
    }
}
